[build-system]
build-backend = "poetry.core.masonry.api"
requires = [ "poetry-core" ]

[tool.poetry]
name = "api-response-shaper"
version = "1.4.0"
description = "An essential package for structuring and optimizing your API responses."
license = "MIT"
authors = [ "ARYAN-NIKNEZHAD <aryan513966@gmail.com>", "MEHRSHAD-MIRSHEKARY <mehrshad_mirshekary@email.com>" ]
readme = "README.md"
keywords = [ "django", "django-api-shaper", "response-shaper", "shaper" ]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Web Environment",
  "Framework :: Django",
  "Framework :: Django :: 5.2",
  "Framework :: Django :: 6.0",
  "Framework :: Django :: 6.1",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [
  { include = "response_shaper" },
]
dependencies.python = ">=3.10,<3.15"
dependencies.django = [
  { version = ">=5.2,<6.0", python = ">=3.10,<3.12" },
  { version = ">=5.2,<6.2", python = ">=3.12,<3.15" },
]
dependencies.djangorestframework = ">=3.18,<3.19"
group.dev.dependencies.bandit = { extras = [ "toml" ], version = "^1.7.9" }
group.dev.dependencies.black = "^24.4.2"
group.dev.dependencies.codecov = "^2.1.13"
group.dev.dependencies.commitizen = "^3.28.0"
group.dev.dependencies.django-stubs = "^5.0.4"
group.dev.dependencies.docformatter = "^1.7.5"
group.dev.dependencies.isort = "^5.13.2"
group.dev.dependencies.mypy = "^1.11.1"
group.dev.dependencies.pre-commit = "^3.5.0"
group.dev.dependencies.pylint = "^3.2.6"
group.dev.dependencies.pylint-django = "^2.5.5"
group.dev.dependencies.pytest = "^8.3.2"
group.dev.dependencies.pytest-asyncio = "^0.25.3"
group.dev.dependencies.pytest-cov = "^5.0.0"
group.dev.dependencies.pytest-django = "^4.8.0"
group.dev.dependencies.python-semantic-release = "^9.8.8"
group.dev.dependencies.sphinx = "^6.2.1"
group.dev.dependencies.sphinx-rtd-theme = "^2.0.0"
group.dev.dependencies.tox = "^4.16.0"
urls."Source Code" = "https://github.com/Lazarus-org/api-response-shaper"
urls.Changelog = "https://github.com/lazarus-org/api-response-shaper/blob/main/CHANGELOG.md"
urls.Issues = "https://github.com/lazarus-org/api-response-shaper/issues"

[tool.black]
line-length = 88
exclude = '''
/(
    \.git
  | \.venv
  | \.tox
  | build
  | dist
  | migrations
  | venv
  | env
  | __pycache__
  | node_modules
  | env
  | kernel
  | \.mypy_cache
  | \.pytest_cache
  | .*\.egg-info
)/
'''

[tool.isort]
profile = "black"
line_length = 88
skip = [
  "*.egg-info",
  ".git",
  ".mypy_cache",
  ".pytest_cache",
  ".tox",
  ".venv",
  "__pycache__",
  "build",
  "dist",
  "env",
  "kernel",
  "migrations",
  "node_modules",
  "venv",
]

[tool.pylint]
argument-rgx = "[a-z_][a-z0-9_]{2,30}$"
attr-rgx = "[a-z_][a-z0-9_]{2,30}$"
class-rgx = "[A-Z_][a-zA-Z0-9]+$"
const-rgx = "([A-Z_][A-Z0-9_]*)|(__.*__)"
disable = [
  "C0103", # Invalid constant name
  "C0114", # Missing module docstring
  "C0115", # Missing class docstring
  "C0116", # Missing function or method docstring
  "C0301", # Line too long
  "C0411", # Wrong import order
  "C0415",
  "E1101", # Instance of 'Foo' has no 'bar' member
  "R0401",
  "R0801", # Duplicate code
  "R0903", # Too few public methods
  "R0911",
  "R0913",
  "R1705", # Unnecessary "elif" after "return"
  "R1719", # The if expression can be replaced with 'bool(test)'
  "W0143",
  "W0212", # Access to a protected member
  "W0231",
  "W0611", # Unused imports
  "W0613", # Unused arguments
  "W0621",
  "W0622", # Redefining built-in names
]
django-settings-module = "kernel.settings"
function-rgx = "[a-z_][a-z0-9_]{2,30}$"
ignore = [
  "*.egg-info/*",
  ".git/*",
  ".mypy_cache/*",
  ".pytest_cache/*",
  ".tox/*",
  "__pycache__/*",
  "build/*",
  "dist/*",
  "migrations/*",
  "tests",
  "venv/*",
]
load-plugins = [
  "pylint_django",
  "pylint.extensions.docparams",
]
max-line-length = 88
max-positional-arguments = 10
method-rgx = "[a-z_][a-z0-9_]{2,30}$"
module-rgx = "(([a-z_][a-z0-9_]*)|(__.*__))$"
suggestion-mode = true
variable-rgx = "[a-z_][a-z0-9_]{2,30}$"

[tool.bandit]
exclude_dirs = [
  ".git",
  ".tox",
  ".venv",
  "build",
  "dist",
  "migrations",
  "tests",
  "venv",
]
targets = [ "./response_shaper" ]
confidence = "medium"
exclude_tests = [ "B301", "B302" ]
include = [ "*.py" ]
max_lines = 500
output_file = "bandit_report.txt"
output_format = "screen"
plugins.B104 = { check_typed_list = true }
progress = true
reports = true
severity = "medium"

[tool.mypy]
mypy_path = "stubs"
exclude = """
^docs/source/conf.py|
^build/|
^tests/|
^stubs/|
^kernel/
"""
explicit_package_bases = true
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true

[tool.pytest]
ini_options.norecursedirs = [
  ".tox",
  ".venv",
  "build",
  "dist",
  "env",
  "kernel",
  "migrations",
  "venv",
]
ini_options.python_files = [ "test_*.py", "tests.py" ]
ini_options.addopts = "--cov --cov-report=term-missing --cov-report=html --cov-fail-under=90"
ini_options.markers = [
  "api_responses: Tests api responses",
  "decorators: Test decorators for api responses",
  "exceptions: Test exceptions and error handlers",
  "middleware: Test Dynamic middleware",
  "settings: Test settings",
]

[tool.coverage]
run.source = [ "response_shaper" ]
run.omit = [
  "*/apps.py*",
  "*/migrations/*",
  "*/tests/*",
]
report.exclude_lines = [
  "def __repr__",
  "if __name__ == .__main__.:",
  "if 0:",
  "if self\\.debug",
  "pragma: no cover",
  "raise AssertionError",
]

[tool.commitizen]
name = "cz_conventional_commits"
version = "1.4.0"
version_files = [ "pyproject.toml" ]
tag_format = "v$version"
settings.increment_types = [ "feat", "fix" ]

[tool.semantic_release]
tag_format = "v{version}"
major_on_zero = true
allow_zero_version = true
# version_variables = [ "django_notification/version.py:__version__" ]
build_command_env = []
no_git_verify = false
assets = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_author.default = "semantic-release <semantic-release>"
commit_author.env = "GIT_COMMIT_AUTHOR"
logging_use_named_masks = false
commit_parser = "emoji"
commit_parser_options.allowed_tags = [
  "build",
  "chore",
  "ci",
  "docs",
  "feat",
  "fix",
  "perf",
  "style",
  "refactor",
  "test"
]
commit_parser_options.default_bump_level = 0
commit_parser_options.minor_tags = [ "feat" ]
commit_parser_options.parse_emoji = true
commit_parser_options.patch_tags = [ "fix", "perf" ]
branches.main.match = "(main|master)"
branches.main.prerelease_token = "rc"
branches.main.prerelease = false
publish.dist_glob_patterns = [ "dist/*" ]
publish.upload_to_vcs_release = true
changelog.changelog_file = "CHANGELOG.md"
changelog.environment.autoescape = true
changelog.environment.block_end_string = "%}"
changelog.environment.block_start_string = "{%"
changelog.environment.comment_end_string = "#}"
changelog.environment.comment_start_string = "{#"
changelog.environment.extensions = []
changelog.environment.keep_trailing_newline = false
changelog.environment.lstrip_blocks = false
changelog.environment.newline_sequence = "\n"
changelog.environment.trim_blocks = false
changelog.environment.variable_end_string = "}}"
changelog.environment.variable_start_string = "{{"
changelog.exclude_commit_patterns = []
changelog.template_dir = "templates"
remote.ignore_token_for_push = false
remote.insecure = false
remote.name = "origin"
remote.token = ""
remote.type = "github"
